version: "3.8"

services:
     # Flask Backend Application
     backend:
          build:
               context: ..
               dockerfile: docker/Dockerfile
          container_name: resume_ai_backend
          ports:
               - "${PORT:-8081}:5000"
          environment:
               - FLASK_APP=${FLASK_APP:-run.py}
               - FLASK_ENV=${FLASK_ENV:-production}
               - SECRET_KEY=${SECRET_KEY}
               - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${DB_PASSWORD}@db:5432/${POSTGRES_DB:-resume_ai}
               - JWT_SECRET_KEY=${JWT_SECRET_KEY}
               - OPENAI_API_KEY=${OPENAI_API_KEY}
               - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
               - UPLOAD_FOLDER=${UPLOAD_FOLDER:-uploads}
               - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-10485760}
               - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
               - DEBUG=${DEBUG:-False}
               - LOG_LEVEL=${LOG_LEVEL:-INFO}
               - CORS_ORIGINS=${CORS_ORIGINS:-*}
          volumes:
               # Only mount uploads directory, not entire source code for production
               - resume_ai_uploads:/app/uploads
               - ../app/static:/app/app/static:ro
          depends_on:
               - db
               - redis
          networks:
               - resume_ai_network
          restart: unless-stopped
          healthcheck:
               test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
               interval: 30s
               timeout: 10s
               retries: 3
               start_period: 40s

     # PostgreSQL Database
     db:
          image: postgres:14-alpine
          container_name: resume_ai_db
          environment:
               - POSTGRES_DB=${POSTGRES_DB:-resume_ai}
               - POSTGRES_USER=${POSTGRES_USER:-postgres}
               - POSTGRES_PASSWORD=${DB_PASSWORD}
               - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
          volumes:
               - postgres_data:/var/lib/postgresql/data
               - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          ports:
               - "5433:5432"
          networks:
               - resume_ai_network
          restart: unless-stopped
          healthcheck:
               test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-resume_ai}"]
               interval: 10s
               timeout: 5s
               retries: 5
          command: >
               postgres
               -c max_connections=200
               -c shared_buffers=128MB
               -c effective_cache_size=256MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c default_statistics_target=100

     # Redis for Caching and Session Management
     redis:
          image: redis:7-alpine
          container_name: resume_ai_redis
          ports:
               - "6380:6379"
          volumes:
               - redis_data:/data
          networks:
               - resume_ai_network
          restart: unless-stopped
          healthcheck:
               test: ["CMD", "redis-cli", "ping"]
               interval: 10s
               timeout: 3s
               retries: 5
          command: >
               redis-server
               --appendonly yes
               --maxmemory 128mb
               --maxmemory-policy allkeys-lru

     # pgAdmin for Database Management (Development Only)
     pgadmin:
          image: dpage/pgadmin4
          container_name: resume_ai_pgadmin
          environment:
               - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
               - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
          ports:
               - "5050:80"
          depends_on:
               - db
          networks:
               - resume_ai_network
          restart: unless-stopped
          profiles:
               - dev

volumes:
     postgres_data:
          name: resume_ai_postgres_data
          driver: local
     redis_data:
          name: resume_ai_redis_data
          driver: local
     resume_ai_uploads:
          name: resume_ai_uploads
          driver: local

networks:
     resume_ai_network:
          name: resume_ai_network
          driver: bridge
